name: Test FastAPI app

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start FastAPI app
        run: | 
            uvicorn app.main:app --port 8000 --host 0.0.0.0 & background: true
      - name: Wait for app to start
        run: |
          for i in {1..30}; do
            curl -s localhost:8000/docs > /dev/null && break
            sleep 1
          done